### ISSUE TITLE
Implement circle sort

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/PySortDemo#19]
http://www.geeksforgeeks.org/circle-sort/

**Comment by Tardog** [comment]
Hi! Can I work on this?

**Comment by StegSchreck** [comment]
https://github.com/Eckankar/PySortDemo/pull/21

**Comment by Tardog** [comment]
@StegSchreck No problem. I’ve had a look at your code and fiddled around a bit with the markers.

I _think_ the algorithm is working much faster than the display is redrawn. That’s why the markers appear in weird places, or not at all. Only a guess, though. I don’t have any prior experience with pygame.

**Comment by Eckankar** [comment]
The visualization doesn't work correctly due to the algorithm not being implemented as an iterator. :) See https://github.com/Eckankar/PySortDemo/blob/master/CONTRIBUTING.md for more information about structuring the algorithms.
