### ISSUE TITLE
Implement patience sorting

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/PySortDemo#5]
https://en.wikipedia.org/wiki/Patience_sorting

**Comment by MilindaLaknath** [comment]
@Eckankar 

I will do it.

Thank You.

**Comment by sapanshah** [comment]
I'd like to try this one.

**Comment by Eckankar** [comment]
@sapanshah I believe that @xiroV may already be working on this?

**Comment by xiroV** [comment]
Yea, my apologies. I am.

**Comment by sapanshah** [comment]
Okay, cool
