### ISSUE TITLE
Implement JSort

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/PySortDemo#7]
https://xlinux.nist.gov/dads/HTML/JSort.html

http://home.westman.wave.ca/~rhenry/sort/src/JSortAlgorithm.java

**Comment by MilindaLaknath** [comment]
@Eckankar 

I will do it.

Thank You.

**Comment by divyanshu-talwar** [comment]
Hey! 
How should I put the markers to show the sorting flow?
Please give me an idea I have already implemented the sorting part with yield...

**Comment by Eckankar** [comment]
@divyanshu-talwar You might be able to take some inspiration from [the Heapsort implementation](https://github.com/Eckankar/PySortDemo/blob/master/Algorithms/HeapSort.py)

I think that's the best I can do; I don't have any better ideas. :)

**Comment by divyanshu-talwar** [comment]
Okay, thank you :)
PR coming soon... :P

**Comment by divyanshu-talwar** [comment]
Hey! So while implementing SiftSort I noticed something....
It nearly sorts the data and then takes quite too long to process the nearly sorted data (till now it is unable to sort the given data completely)
What should I do now?
Should I just set up a threshold and then apply insertion sort on the nearly sorted data...

**Comment by Eckankar** [comment]
@divyanshu-talwar As mentionen in the TODO, I was mainly curious to see if it actually was a sort. Leave it as is. 👍
