### ISSUE TITLE
Implement in-place merge sort

### ISSUE THREAD

**Issue by Eckankar** [Eckankar/PySortDemo#9]
http://www.cs.ubc.ca/~harrison/Java/MergeSortAlgorithm.java.html

**Comment by theharshitgarg** [comment]
Hello, 
I want to contribute by writing the code. Can you please tell me how to go about it. I know Java and the algorithm. But do not know how to contribute.

**Comment by Eckankar** [comment]
Hey! Thanks for your interest.

I have created a [CONTRIBUTING.md](https://github.com/Eckankar/PySortDemo/blob/master/CONTRIBUTING.md) you can take a look at. If you have any further questions, feel free to let me know.

**Comment by divyanshu-talwar** [comment]
Hey!
I wish to contribute to your repository. Can you please tell me the language you want the above-mentioned algorithm to be written in.
Thanks :)

**Comment by Eckankar** [comment]
@divyanshu-talwar It needs to follow the current implementation, so Python 2.

**Comment by divyanshu-talwar** [comment]
Okay thanks :) 
Will get back to you in an hour or two.
